### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by walkintom** [autopkg/aysiu-recipes#17] opened 2018-07-16 13:33 UTC
When running `autopkg make-override com.github.aysiu.munki.Burn`

`Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 2453, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2447, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1782, in make_override
    recipe, search_dirs=search_dirs)
  File "/usr/local/bin/autopkg", line 1389, in get_trust_info
    'path': os_path_compressuser(processor_path),
  File "/usr/local/bin/autopkg", line 1349, in os_path_compressuser
    elif pathname.startswith(home_dir):
AttributeError: 'NoneType' object has no attribute 'startswith'`

**Comment by gregneagle** [comment] 2018-07-16 13:54
As you discovered in Slack that's not an issue with the recipe. It was caused by the fact you didn't have a parent recipe available, which you could fix by adding the repo containing the missing parent recipe.

The real issue here is that make-override is not providing useful error messages in this situation. I'd suggest closing this issue and opening a new one against autopkg.

**Closed** 2019-03-11 16:35 UTC
